# Generated by Django 3.2.4 on 2021-06-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(max_length=5)),
                ('emp_name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=50)),
                ('salary', models.IntegerField(max_length=10)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
